services:
  postgres:
    container_name: postgres_go
    image: postgres:16.4
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - '5432:5432'
